# Generated by Django 4.2.15 on 2024-09-03 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='menuitem',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='named_url',
        ),
    ]
